---
# Afvalbeheer
# 
# https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer
#
- platform: afvalbeheer
  wastecollector: RecycleApp
  resources:
    - restafval
    - papier
    - pmd
    - glas
  postcode: !secret address_postal_code
  streetnumber: !secret address_streetnumber
  streetname: !secret address_streetname
  cityname: !secret address_cityname
  upcomingsensor: 1
