---
# The command_line sensor platform simply issues specific commands to get its data. 
#
# https://www.home-assistant.io/integrations/sensor.command_line/
#

# Buienalarm en -radar
- platform: command_line
  command: python3 -c "import requests; import json; import random; dataRequest = requests.get('https://cdn-secure.buienalarm.nl/api/3.4/forecast.php?lat={{state_attr("zone.home", "latitude") | round(2)}}&lon={{state_attr("zone.home", "longitude") | round(2)}}&region=nl&unit=mm%2Fu&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":'+dataRequest+'}';    print(data);"
  name: Neerslag Buienalarm Regen Data
  json_attributes:
    - data
  value_template: 'last_changed: {{states.sensor.neerslag_buienalarm_regen_data.last_changed}}'
  scan_interval: 240
- platform: command_line
  command: python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat={{state_attr("zone.home", "latitude") | round(2)}}&lon={{state_attr("zone.home", "longitude") | round(2)}}&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    print(data);"
  name: Neerslag Buienradar Regen Data
  json_attributes:
    - data
  value_template: 'last_changed: {{states.sensor.neerslag_buienradar_regen_data.last_changed}}'
  scan_interval: 240
