---
# The epson workforce platform allows you to monitor the ink levels of
# a Epson Workforce printer from Home Assistant.
#
# https://www.home-assistant.io/integrations/epsonworkforce/
#
- platform: epsonworkforce
  host: epsona334ef.local
  monitored_conditions:
  - black
  - yellow
  - magenta
  - cyan
