---
# The GoodWe Inverter Solar Sensor component will retrieve data from a GoodWe inverter
# connected to local network (via UDP).
#
# https://github.com/mletenay/home-assistant-goodwe-inverter
#
- platform: goodwe
  ip_address: !secret ip_inverter
  #port: 8899
  #network_timeout: 2
  #network_retries: 3
  #scan_interval: 30
  #sensor_name_prefix: GoodWe
