---
# The systemmonitor sensor platform allows you to monitor disk usage, memory usage,
# CPU usage, and running processes.
#
# https://www.home-assistant.io/integrations/systemmonitor/
#
- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /config
    - type: memory_free
    - type: processor_use
    - type: processor_temperature
    - type: network_in
      arg: eth0
    - type: network_out
      arg: eth0
