---
# The waze_travel_time sensor provides travel time from Waze.
#
# https://www.home-assistant.io/integrations/waze_travel_time/
#
- platform: waze_travel_time
  name: Home - Work
  origin: zone.home
  destination: zone.in_the_pocket
  region: "EU"
- platform: waze_travel_time
  name: Home - School
  origin: zone.home
  destination: zone.school
  region: "EU"
