---
# Grouping notifiy devices for easy access, since you can't change the entity IDs
#
# https://www.home-assistant.io/integrations/notify.group/
#
- platform: group
  name: "Lode Devices"
  services:
    - service: mobile_app_iphone_14_pro
    - service: mobile_app_macbook_pro_lode

- platform: group
  name: "Ellen Devices"
  services:
    - service: mobile_app_iphone_13_ellen

- platform: group
  name: "Parents Devices"
  services:
    - service: mobile_app_iphone_14_pro
    - service: mobile_app_macbook_pro_lode
    - service: mobile_app_iphone_13_ellen

- platform: group
  name: "Otis Devices"
  services:
    - service: mobile_app_ipad_air_otis

- platform: group
  name: "Juna Devices"
  services:
    - service: mobile_app_ipad_air_juna

- platform: group
  name: "Children Devices"
  services:
    - service: mobile_app_ipad_air_juna
    - service: mobile_app_ipad_air_otis
