- id: '1621927850930'
  alias: "\U0001F4F9 Turn on \"privacy mode\" of camera when people at home"
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.no_one_home
    from: 'on'
    to: 'off'
  condition: []
  action:
  - service: switch.turn_on
    data: {}
    target:
      entity_id: switch.tapo_camera_privacy
  mode: single
- id: '1621928552564'
  alias: "\U0001F4F9 Turn off \"privacy mode\" of camera when no people at home"
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.no_one_home
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: switch.turn_off
    data: {}
    target:
      entity_id: switch.tapo_camera_privacy
  mode: single
- id: 0c363e5fa5164f67b91bafc26f04de05
  alias: ♻️ Send garbage reminder
  trigger:
  - platform: state
    entity_id:
    - sensor.recycleapp_tomorrow
  condition:
  - condition: template
    value_template: '{{ states.sensor.recycleapp_tomorrow.state != ''None'' }}'
  action:
  - delay:
      hours: 18
      minutes: 0
      seconds: 0
      milliseconds: 0
  - service: notify.lode_devices
    data:
      title: ♻️ Afvalophaling
      message: 'Morgen worden volgende zaken opgehaald: {{ states.sensor.recycleapp_morgen.state
        }}'
  mode: single
- id: '1632921047367'
  alias: "⛱ \U0001F327 Close awning and screen when rain predicted"
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.buienalarm_precipitation_forecast_average
    above: '0.1'
  condition:
  - condition: or
    conditions:
    - condition: numeric_state
      entity_id: cover.screen
      attribute: current_position
      below: 100
    - condition: state
      entity_id: cover.awning
      state: open
  action:
  - service: cover.close_cover
    target:
      entity_id: cover.awning
    data: {}
  - service: cover.open_cover
    data: {}
    target:
      entity_id: cover.screen
  - service: notify.lode_devices
    data:
      title: "\U0001F327 Luifel en screen gesloten door regen"
      message: De luifel en screen werden automatisch gesloten omdat er regen werd
        voorspeld in de komende 15 minuten.
  mode: single
- id: '1632928778074'
  alias: "⛱ \U0001F699 When nobody at home close awning"
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.no_one_home
    from: 'off'
    to: 'on'
    for:
      hours: 0
      minutes: 30
      seconds: 0
  condition:
  - condition: state
    entity_id: cover.awning
    state: open
  action:
  - service: cover.close_cover
    target:
      entity_id: cover.awning
    data: {}
  mode: single
- id: '1636128250859'
  alias: "\U0001F634 Inform kids about bedtime"
  description: ''
  trigger:
  - platform: time
    at: input_datetime.bedtime_report_time
  condition:
  - condition: state
    entity_id: binary_sensor.no_one_home
    state: 'off'
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - sun
  action:
  - service: script.announce_message
    data:
      message: Het is tijd om te gaan slapen! Naar boven, pyjama aan en tanden poetsen!
        Hup hup.
  mode: single
- id: '1636129149096'
  alias: "\U0001F4DA Inform kids about homework"
  description: ''
  trigger:
  - platform: time
    at: input_datetime.homework_report_time
  condition:
  - condition: state
    entity_id: binary_sensor.no_one_home
    state: 'off'
  - condition: time
    weekday:
    - mon
    - tue
    - thu
  action:
  - service: script.cast_message
    data:
      message: Tijd om huiswerk te maken!
  mode: single
- id: '1636131173499'
  alias: "\U0001F4F5 Device offline notification"
  trigger:
  - platform: state
    entity_id:
    - light.led_fridge_left
    - light.led_fridge_right
    - light.led_tv_left
    - light.led_tv_center
    - light.led_tv_right
    - light.led_office_desk_left
    - light.led_office_desk_center
    - light.led_office_desk_right
    - light.led_office_wall_left
    - light.led_office_wall_right
    - light.led_office_mood
    - light.led_strip_otis
    - light.led_strip_juna
    - light.led_kitchen_right
    - light.led_kitchen_left
    to: unavailable
    for:
      minutes: 5
  action:
  - service: notify.lode_devices
    data:
      title: Device offline detected!
      message: "\U0001F4F5 The device {{ state_attr(trigger.to_state.entity_id, 'friendly_name')
        }} is offline!"
      data:
        priority: high
        ttl: 0
        color: red
  mode: parallel
- id: '1637251279206'
  alias: "\U0001F6AA Instruct kids to leave for school"
  description: ''
  trigger:
  - platform: time
    at: input_datetime.leave_for_school_report_time
  condition:
  - condition: state
    entity_id: binary_sensor.no_one_home
    state: 'off'
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - service: script.cast_message
    data:
      message: Tijd om je klaar te maken voor school!
  mode: single
- id: '1638859694197'
  alias: "\U0001F976 Fridge plug turned off notification"
  description: ''
  trigger:
  - platform: state
    to: 'off'
    for:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 0
    entity_id: switch.smart_plug_fridge
  condition: []
  action:
  - service: notify.lode_devices
    data:
      title: Device offline detected!
      message: "\U0001F976 The fridge plug was turned off!"
      data:
        priority: high
        ttl: 0
        color: red
  mode: parallel
  max: 10
- id: '1638957877743'
  alias: "\U0001F4F9 Turn off \"privacy mode\" at night"
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.night
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: switch.turn_off
    data: {}
    target:
      entity_id: switch.tapo_camera_privacy
  mode: single
- id: '1638957990044'
  alias: "\U0001F4F9 Turn on \"privacy mode\" at day"
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.day
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: switch.turn_on
    data: {}
    target:
      entity_id: switch.tapo_camera_privacy
  mode: single
- id: '1650973895443'
  alias: "\U0001F699 Ellen leaves from work"
  description: ''
  trigger:
  - platform: zone
    entity_id: person.ellen_ophalvens
    zone: zone.okra
    event: leave
  condition: []
  action:
  - service: notify.lode_devices
    data:
      message: Ellen vertrok zonet van haar werk. Over {{ states.sensor.okra_home.state
        }} minuten is ze thuis.
      title: "\U0001F699 Ellen op weg naar huis!"
  mode: single
- id: '1657788008411'
  alias: "⛱ \U0001F32C Close awning when a lot of wind predicted"
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: weather.home
    above: '20'
    attribute: wind_speed
  condition:
  - condition: state
    entity_id: cover.awning
    state: open
  action:
  - service: cover.close_cover
    target:
      entity_id: cover.awning
    data: {}
  - service: notify.lode_devices
    data:
      message: De luifel werd gesloten omdat er hardere wind wordt voorspeld.
      title: "\U0001F32C Luifel gesloten door wind"
  mode: single
- id: '1657790977221'
  alias: ⛱ ☀️ Open awning when too bright sunlight and not windy and before 15h30
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.outdoor_luminance
    above: 70000
  - platform: time
    at: 08:15:00
  condition:
  - condition: numeric_state
    entity_id: weather.home
    below: '20'
    attribute: wind_speed
  - condition: state
    state: closed
    entity_id: cover.awning
  - condition: time
    before: '15:30:00'
  action:
  - service: cover.set_cover_position
    data:
      position: 60
    target:
      entity_id: cover.awning
  - service: notify.lode_devices
    data:
      message: Luifel wordt automatisch geopend omdat helderheid te hoog is (en geen
        harde wind).
      title: ⛱ Luifel wordt geopend
  mode: single
- id: '1657791504056'
  alias: ⛱ ☀️ Close screen when too bright sunlight
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.outdoor_luminance
    above: 100000
  condition:
  - condition: state
    entity_id: cover.screen
    state: open
  action:
  - service: cover.close_cover
    data: {}
    target:
      entity_id: cover.screen
  - service: notify.lode_devices
    data:
      message: Screen wordt automatisch gesloten omdat helderheid te hoog is.
      title: ⛱ Screen wordt gesloten
  mode: single
- id: '1657791651788'
  alias: ⛱ ⏱ Open screen at 21h00
  description: ''
  trigger:
  - platform: time
    at: '21:00:00'
  condition:
  - condition: numeric_state
    entity_id: cover.screen
    attribute: current_position
    below: '100'
  action:
  - service: cover.open_cover
    data: {}
    target:
      entity_id: cover.screen
  - service: notify.lode_devices
    data:
      title: ⛱ Screen openen (avond)
      message: Screen wordt automatisch geopend omdat het avond is.
  mode: single
- id: '1657793011369'
  alias: ⛱ ⏱ Close awning at 15h30
  description: ''
  trigger:
  - platform: time
    at: '15:30:00'
  condition:
  - condition: state
    entity_id: cover.awning
    state: open
  action:
  - service: cover.close_cover
    data: {}
    target:
      entity_id: cover.awning
  - service: notify.lode_devices
    data:
      title: ⛱ Luifel gesloten (schaduw)
      message: Luifel wordt wordt automatisch gesloten omdat er genoeg schaduw is.
  mode: single
- id: '1663504824526'
  alias: ☀️⚡️⬆️ Upload solar panel production to EnergyID
  description: ''
  trigger:
  - platform: time_pattern
    hours: '23'
    minutes: '59'
    seconds: '0'
  condition: []
  action:
  - service: energy_id.set_meter_reading
    data:
      device_id: 40beff9400472b34909cdd9d8852d748
      value: '{{ states(''sensor.inverter_solar_energy'') }}'
      date: '{{ now().isoformat() }}'
  mode: single
- id: '1663759782665'
  alias: Dishwasher finished
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.smart_plug_dishwasher_power
    below: 20
    for:
      hours: 0
      minutes: 20
      seconds: 0
  condition: []
  action:
  - service: notify.parents_devices
    data:
      title: "\U0001F37D️ The dishwasher is ready"
      message: The dishwasher has finished its cleaning cycle.
  mode: single
- id: '1663760300053'
  alias: Washing machine finished
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.smart_plug_washer_power
    below: 15
    for:
      hours: 0
      minutes: 15
      seconds: 0
  condition: []
  action:
  - service: notify.parents_devices
    data:
      title: "\U0001F9FA \U0001FAE7 Washing machine ready"
      message: The washing machine has finished its cycle.
  mode: single
- id: '1663760560002'
  alias: Dryer finished
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.smart_plug_dryer_power
    below: 15
    for:
      hours: 0
      minutes: 5
      seconds: 0
  condition: []
  action:
  - service: notify.parents_devices
    data:
      title: "\U0001F455 The dryer is ready"
      message: The dryer has finished its cycle.
  mode: single
- id: '1666771838886'
  alias: "\U0001F30D Warn when internet connection offline"
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.internet
    from: 'on'
    to: 'off'
  condition: []
  action:
  - service: notify.lode_devices
    data:
      message: "\U0001F30D The internet connection is offline!"
      data:
        priority: high
        ttl: 0
        color: red
      title: Internet connection offline!
  mode: parallel
- id: '1666771910607'
  alias: "\U0001F30D Inform when internet connection has been restored"
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.internet
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: notify.lode_devices
    data:
      title: Internet connectivity has been restored.
      message: "\U0001F30D The internet connection is online again!"
  mode: parallel
- id: '1673022556063'
  alias: Wake up iPad Mini when motion detected
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.motion_detected_in_living_room
    to: 'on'
  condition:
  - condition: state
    entity_id: binary_sensor.no_one_home
    state: 'off'
  action:
  - service: notify.mobile_app_ipad_mini_otis
    data:
      title: Wake up!
      message: Waking you up, since motion was detected.
  mode: single
- id: '1673380802036'
  alias: Set dark theme when sun sets
  description: ''
  trigger:
  - platform: sun
    event: sunset
  condition: []
  action:
  - service: frontend.set_theme
    data:
      mode: dark
      name: Mushroom Custom
  mode: single
- id: '1673380823820'
  alias: Set light theme when sun rises
  description: ''
  trigger:
  - platform: sun
    event: sunrise
  condition: []
  action:
  - service: frontend.set_theme
    data:
      mode: light
      name: Mushroom Custom
  mode: single
- id: '1684871922041'
  alias: "\U0001F440 Send notification when privacy mode off"
  description: ''
  trigger:
  - platform: state
    entity_id:
    - switch.tapo_camera_privacy
    from: 'on'
    to: 'off'
  condition: []
  action:
  - service: notify.lode_devices
    data:
      message: Privacy mode of the Tapo webcam was disabled.
      title: "\U0001F440 Privacy mode disabled"
  mode: single
