---
# The template platform creates switches that combines components.
#
# https://www.home-assistant.io/integrations/switch.template/
#

# Camera
- platform: template
  switches:
    # This is a switch to turn the privacy mode on/off
    camera_privacy_mode:
      friendly_name: Privacy Mode
      value_template: "{{ state_attr('camera.tapo_camera_hd', 'privacy_mode') == 'on' }}"
      turn_on:
        service: tapo_control.set_privacy_mode
        data:
          entity_id: "camera.tapo_camera_hd"
          privacy_mode: "on"
      turn_off:
        service: tapo_control.set_privacy_mode
        data:
          entity_id: "camera.tapo_camera_hd"
          privacy_mode: "off"
      icon_template: >-
        {% if state_attr('camera.tapo_camera_hd', 'privacy_mode') == 'on' %}
          mdi:eye-off-outline
        {% else %}
          mdi:eye-outline
        {% endif %}
    # This is a switch to turn the auto track mode on/off
    camera_auto_track:
      friendly_name: Auto Track
      value_template: "{{ state_attr('camera.tapo_camera_hd', 'auto_track') == 'on' }}"
      turn_on:
        - service: tapo_control.set_auto_track_mode
          data:
            entity_id: camera.tapo_camera_hd
            auto_track_mode: 'on'
      turn_off:
        - service: tapo_control.set_auto_track_mode
          data:
            entity_id: camera.tapo_camera_hd
            auto_track_mode: 'off'
      icon_template: "mdi:radar"
    # This is a switch to turn the alarm on/off
    camera_alarm:
      friendly_name: Alarm
      value_template: "{{ state_attr('camera.tapo_camera_hd', 'alarm') == 'on' }}"
      turn_on:
        - service: tapo_control.set_alarm_mode
          data:
            entity_id: camera.tapo_camera_hd
            alarm_mode: 'on'
      turn_off:
        - service: tapo_control.set_alarm_mode
          data:
            entity_id: camera.tapo_camera_hd
            alarm_mode: 'off'
      icon_template: >-
        {% if state_attr('camera.tapo_camera_hd', 'alarm') == 'on' %}
          mdi:alarm-note
        {% else %}
          mdi:alarm-note-off
        {% endif %}
