---
# This is the workday sensor. This binary sensor tells me if it is
# a workday today. It takes into account holidays as well!
#
# This is pretty useful for a lot of automations.
#
# https://www.home-assistant.io/integrations/workday/
#
- platform: workday
  name: Workday
  country: BE
  workdays:
    - mon
    - tue
    - wed
    - thu
    - fri
  excludes: [sat, sun]
- platform: workday
  name: Weekend
  country: BE
  workdays:
    - sat
    - sun
  excludes: [mon, tue, wed, thu, fri]
- platform: workday
  name: Schoolday
  country: BE
  workdays:
    - mon
    - tue
    - wed
    - thu
    - fri
  excludes: [sat, sun, holiday]
  add_holidays:
    - '2022-04-01'
    - '2022-04-02'
    - '2022-04-03'
    - '2022-04-04'
    - '2022-04-05'
    - '2022-04-06'
