---
- id: '1617823541653'
  alias: Send a camera snapshot when motion is detected
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.tapo_camera_motion
    to: 'on'
  condition:
  - condition: state
    entity_id: binary_sensor.no_one_home
    state: 'on'
  action:
  - service: camera.snapshot
    data:
      filename: /config/www/tmp/snapshot_{{ states('camera.tapo_camera_hd.object_id')
        }}.jpg
    target:
      entity_id: camera.tapo_camera_hd
  - service: notify.lode_devices
    data:
      title: 🚨 Motion detected!
      message: Motion was detected in the living room!
      data:
        image: /local/tmp/snapshot_{{ states('camera.tapo_camera_hd.object_id') }}.jpg
        attachment:
          url: /local/tmp/snapshot_{{ states('camera.tapo_camera_hd.object_id') }}.jpg
  mode: single
