blueprint:
  name: 0.87 Pilocator Alerts
  description: Send an alert when Pilocator posts Raspberry PI availability.  Requires
    feed reader.
  domain: automation
  input:
    notify_device:
      name: Device to notify
      description: Device needs to run the official Home Assistant app to receive
        notifications.
      selector:
        device:
          integration: mobile_app
          multiple: false
    country_code:
      name: Country Code
      default: Stock Alert (
      selector:
        select:
          mode: dropdown
          options:
          - label: (ANY)
            value: Stock Alert (
          - label: (AT)
            value: Stock Alert (AT)
          - label: (AU)
            value: Stock Alert (AU)
          - label: (BE)
            value: Stock Alert (BE)
          - label: (CA)
            value: Stock Alert (CA)
          - label: (CH)
            value: Stock Alert (CH)
          - label: (CN)
            value: Stock Alert (CN)
          - label: (DE)
            value: Stock Alert (DE)
          - label: (ES)
            value: Stock Alert (ES)
          - label: (FR)
            value: Stock Alert (FR)
          - label: (IT)
            value: Stock Alert (IT)
          - label: (NL)
            value: Stock Alert (NL)
          - label: (PL)
            value: Stock Alert (PL)
          - label: (PT)
            value: Stock Alert (PT)
          - label: (SE)
            value: Stock Alert (SE)
          - label: (UK)
            value: Stock Alert (UK)
          - label: (UK)
            value: Stock Alert (UK)
          - label: (US)
            value: Stock Alert (US)
          - label: (ZA)
            value: Stock Alert (ZA)
          custom_value: false
          multiple: false
    pi4:
      name: pi4
      default: --no--
      selector:
        select:
          mode: dropdown
          options:
          - label: 'NO'
            value: --no--
          - label: ANY
            value: RPi 4
          - label: 1GB
            value: RPi 4 Model B - 1GB
          - label: 2GB
            value: RPi 4 Model B - 2GB
          - label: 4GB
            value: RPi 4 Model B - 4GB
          - label: 8GB
            value: RPi 4 Model B - 8GB
          custom_value: false
          multiple: false
    cm4_ram:
      name: cm4
      default: --no--
      selector:
        select:
          mode: dropdown
          options:
          - label: 'NO'
            value: --no--
          - label: ANY
            value: CM4
          - label: 2GB
            value: CM4 - 2GB
          - label: 4GB
            value: CM4 - 4GB
          custom_value: false
          multiple: false
    cm4_wifi:
      name: cm4 Wifi
      default: Wifi
      selector:
        select:
          mode: dropdown
          options:
          - label: ANY
            value: Wifi
          - label: With Wifi
            value: With Wifi
          - label: No Wifi
            value: No Wifi
          custom_value: false
          multiple: false
    cm4_mmc:
      name: cm4 mmc
      default: MMC
      selector:
        select:
          mode: dropdown
          options:
          - label: ANY
            value: MMC
          - label: No MMC
            value: No MMC
          - label: 8GB MMC
            value: 8GB MMC
          - label: 16GB MMC
            value: 16GB MMC
          - label: 32GB MMC
            value: 32GB MMC
          custom_value: false
          multiple: false
    zero_2_w:
      name: Zero 2 W
      default: --NO--
      selector:
        select:
          mode: dropdown
          options:
          - label: 'NO'
            value: --NO--
          - label: ANY
            value: Raspberry Pi Zero 2 W
          custom_value: false
          multiple: false
  source_url: https://community.home-assistant.io/t/rpilocator-notification-blueprint/483197
trigger:
- platform: event
  event_type: feedreader
variables:
  country_code: !input country_code
  pi4: !input pi4
  cm4_ram: !input cm4_ram
  cm4_wifi: !input cm4_wifi
  cm4_mmc: !input cm4_mmc
  zero_2_w: !input zero_2_w
  pi_message: '{{ trigger.event.data.summary }}'
  pi_uri: '{{ trigger.event.data.link }}'
  pi_alert: '{{ (country_code in pi_message and pi4 in pi_message) or (country_code
    in pi_message and cm4_wifi in pi_message and cm4_mmc in pi_message and cm4_ram
    in pi_message) or (country_code in pi_message and zero_2_w in pi_message)  }}'
condition:
  condition: template
  value_template: '{{ pi_alert }}'
action:
- alias: There may be a PI in your future!
  domain: mobile_app
  type: notify
  device_id: !input notify_device
  message: '{{ pi_message + '' v0.87''}}'
  data:
    actions:
    - action: URI
      title: pilocator.com
      uri: '{{ pi_uri }}'
