---
# Kitch light groups
#
# https://www.home-assistant.io/integrations/light.group/
#
- platform: group
  name: Fridge Lights
  entities:
    - light.01242673c82b96c9495d
    - light.01242673c82b96c965c0
