---
# Kitchen light groups
#
# https://www.home-assistant.io/integrations/light.group/
#
- platform: group
  name: Fridge Lights
  unique_id: "76574510-84c4-11ec-a88c-7f7155c6981c"
  entities:
    - light.led_fridge_left
    - light.led_fridge_right
- platform: group
  name: Kitchen Lights
  unique_id: "0ce6f2b0-19fb-4ed8-a463-10988da310a9"
  entities:
    - light.led_kitchen_left
    - light.led_kitchen_right
