---
# Living room light groups
#
# https://www.home-assistant.io/integrations/light.group/
#
- platform: group
  name: TV Spots
  entities:
    - light.led_tv_links
    - light.led_tv_midden
    - light.led_tv_rechts
- platform: group
  name: TV LED Strip
  entities:
    - light.led_strip_tv
