---
# Office light groups
#
# https://www.home-assistant.io/integrations/light.group/
#
- platform: group
  name: Office Ceiling Lights
  entities:
    - light.led_bureau_links
    - light.led_bureau_midden
    - light.led_bureau_rechts
- platform: group
  name: Office Wall Lights
  entities:
    - light.led_bureaukast_links
    - light.led_bureaukast_rechts
- platform: group
  name: Office Mood Light
  entities:
    - light.led_sfeerlicht_bureau
